name: external_exam
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  provider: ^6.0.5
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  flutter_secure_storage: ^8.0.0
  firebase_core: ^2.21.0
  cloud_firestore: ^4.9.0
  # Conditionally include firebase_messaging except for web
  firebase_messaging: ^14.7.0
  qr_flutter: ^4.0.0
  path_provider: ^2.1.1
  flutter_local_notifications: ^19.1.0
  shared_preferences: ^2.5.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.7
  hive_generator: ^2.0.1
  flutter_lints: ^3.0.1

flutter:

  uses-material-design: true
